import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:gal/gal.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:share_plus/share_plus.dart';

import '../../core/constants/app_constants.dart';
import '../../core/theme/app_theme.dart';
import '../../models/rfq_report_data.dart';
import '../../models/trade.dart';
import '../../providers/providers.dart';
import '../../services/negotiation_service.dart';
import '../../services/rfq_docx.dart';
import '../../services/rfq_report_pdf.dart';
import '../../services/trade_service.dart';
import '../shared/negotiation_screen.dart';
import 'create_rfq_screen.dart';

/// Importer's posted RFQs — tap one to view quotations received and accept the best offer.
/// The underlying data source is still TradeService.listMyRFQs(); search/filter/sort below
/// are all done client-side over that same list — no new endpoints.
class MyRFQsScreen extends ConsumerStatefulWidget {
  const MyRFQsScreen({super.key});
  @override
  ConsumerState<MyRFQsScreen> createState() => _MyRFQsScreenState();
}

enum _SortOrder { newest, oldest }

class _MyRFQsScreenState extends ConsumerState<MyRFQsScreen> {
  final _tradeService = TradeService();
  late Future<List<RFQ>> _future;
  final _searchCtrl = TextEditingController();
  String _query = '';
  String _statusFilter = 'All';
  _SortOrder _sort = _SortOrder.newest;

  static const _statuses = ['All', 'open', 'quoted', 'closed', 'cancelled'];

  @override
  void initState() {
    super.initState();
    _future = _tradeService.listMyRFQs();
  }

  void _refresh() => setState(() => _future = _tradeService.listMyRFQs());

  List<RFQ> _applyFilters(List<RFQ> rfqs) {
    var list = rfqs.where((r) {
      if (_statusFilter != 'All' && r.status != _statusFilter) return false;
      if (_query.trim().isEmpty) return true;
      final q = _query.trim().toLowerCase();
      return r.productName.toLowerCase().contains(q) || r.rfqNumber.toLowerCase().contains(q) || r.destinationCountry.toLowerCase().contains(q);
    }).toList();
    list.sort((a, b) => _sort == _SortOrder.newest ? b.createdAt.compareTo(a.createdAt) : a.createdAt.compareTo(b.createdAt));
    return list;
  }

  RfqReportData _reportDataFor(RFQ rfq) {
    final auth = ref.read(authProvider);
    return RfqReportData(
      rfqNumber: rfq.rfqNumber,
      issueDate: '${rfq.createdAt.toLocal()}'.split('.').first,
      status: rfq.status[0].toUpperCase() + rfq.status.substring(1),
      buyerName: auth.currentUser?.fullName ?? '',
      buyerCompany: auth.currentUser?.companyName ?? 'Not specified',
      buyerEmail: auth.currentUser?.email ?? '',
      supplierName: rfq.status == 'quoted' || rfq.status == 'closed' ? 'See quotations for assigned supplier' : 'To be assigned (open RFQ)',
      productName: rfq.productName,
      hsnCode: rfq.hsnCode ?? 'Not specified',
      category: 'Not specified',
      productDescription: rfq.description ?? 'Not specified',
      quantity: rfq.quantity.toString(),
      unit: rfq.unit,
      minOrderQty: 'Not specified',
      packagingType: 'Not specified',
      targetPrice: rfq.targetPrice?.toStringAsFixed(2) ?? 'Not specified',
      currency: 'INR',
      incoterm: 'Not specified',
      originCountry: 'Not specified',
      destinationCountry: rfq.destinationCountry,
      shippingMode: 'Not specified',
      deliveryDeadline: 'Not specified',
      qualityRequirements: '',
      certifications: '',
      inspectionRequired: false,
      packagingInstructions: '',
      additionalNotes: '',
    );
  }

  Future<void> _duplicate(RFQ rfq) async {
    final created = await Navigator.of(context).push<bool>(
      MaterialPageRoute(builder: (_) => CreateRFQScreen(duplicateFrom: _reportDataFor(rfq))),
    );
    if (created == true) _refresh();
  }

  Future<void> _share(RFQ rfq) async {
    final d = _reportDataFor(rfq);
    await Share.share('''
RFQ ${d.rfqNumber}
Product: ${d.productName}
Quantity: ${d.quantity} ${d.unit}
Target Price: ${d.targetPrice}
Destination: ${d.destinationCountry}
Status: ${d.status}

Generated by ${AppConstants.appName}
''');
  }

  Future<void> _downloadPdf(RFQ rfq) async {
    final bytes = await buildRfqReportPdf(_reportDataFor(rfq), title: 'RFQ Report');
    await Printing.layoutPdf(onLayout: (_) async => bytes, name: 'rfq-${rfq.rfqNumber}.pdf');
  }

  Future<void> _downloadDocx(RFQ rfq) async {
    final d = _reportDataFor(rfq);
    final bytes = buildRfqDocx(
      title: 'RFQ Report',
      companyName: AppConstants.appName,
      rfqNumber: d.rfqNumber,
      issueDate: d.issueDate,
      fields: [
        RfqDocxField('Buyer', '${d.buyerName} (${d.buyerCompany})'),
        RfqDocxField('Product Name', d.productName),
        RfqDocxField('HS Code', d.hsnCode),
        RfqDocxField('Quantity', '${d.quantity} ${d.unit}'),
        RfqDocxField('Target Price', d.targetPrice),
        RfqDocxField('Destination', d.destinationCountry),
        RfqDocxField('Status', d.status),
      ],
      termsAndConditions: RfqReportData.termsAndConditions,
      footer: 'Generated by ${AppConstants.appName}',
    );
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/rfq-${d.rfqNumber}.docx');
    await file.writeAsBytes(bytes);
    await Share.shareXFiles([XFile(file.path)], text: 'RFQ ${d.rfqNumber}');
  }

  Future<void> _downloadImage(RFQ rfq) async {
    final key = GlobalKey();
    final overlay = OverlayEntry(
      builder: (ctx) => Positioned(
        left: -2000,
        child: Material(
          child: RepaintBoundary(
            key: key,
            child: SizedBox(width: 380, child: _RfqDocumentPreview(data: _reportDataFor(rfq))),
          ),
        ),
      ),
    );
    Overlay.of(context).insert(overlay);
    await Future.delayed(const Duration(milliseconds: 50));
    try {
      final boundary = key.currentContext!.findRenderObject() as RenderRepaintBoundary;
      final image = await boundary.toImage(pixelRatio: 3.0);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      final bytes = byteData!.buffer.asUint8List();
      await Gal.requestAccess();
      await Gal.putImageBytes(bytes, name: 'rfq-${rfq.rfqNumber}');
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Report Saved Successfully'), backgroundColor: AppColors.success));
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Could not save image: $e'), backgroundColor: AppColors.error));
    } finally {
      overlay.remove();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('My RFQs')),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () async {
          final created = await Navigator.of(context).push<bool>(MaterialPageRoute(builder: (_) => const CreateRFQScreen()));
          if (created == true) _refresh();
        },
        icon: const Icon(Icons.add),
        label: const Text('New RFQ'),
      ),
      body: RefreshIndicator(
        onRefresh: () async => _refresh(),
        child: FutureBuilder<List<RFQ>>(
          future: _future,
          builder: (context, snapshot) {
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const Center(child: CircularProgressIndicator());
            }
            if (snapshot.hasError) {
              return Center(child: Text('Error: ${snapshot.error}'));
            }
            final all = snapshot.data ?? [];
            final rfqs = _applyFilters(all);

            return CustomScrollView(
              slivers: [
                SliverToBoxAdapter(
                  child: Padding(
                    padding: const EdgeInsets.fromLTRB(16, 16, 16, 0),
                    child: TextField(
                      controller: _searchCtrl,
                      onChanged: (v) => setState(() => _query = v),
                      decoration: InputDecoration(
                        hintText: 'Search by product, RFQ number, or destination',
                        prefixIcon: const Icon(Icons.search),
                        suffixIcon: _query.isNotEmpty
                            ? IconButton(icon: const Icon(Icons.close, size: 18), onPressed: () { _searchCtrl.clear(); setState(() => _query = ''); })
                            : null,
                      ),
                    ),
                  ),
                ),
                SliverToBoxAdapter(
                  child: Padding(
                    padding: const EdgeInsets.fromLTRB(16, 12, 16, 4),
                    child: Row(
                      children: [
                        Expanded(
                          child: SizedBox(
                            height: 40,
                            child: ListView.separated(
                              scrollDirection: Axis.horizontal,
                              itemCount: _statuses.length,
                              separatorBuilder: (_, __) => const SizedBox(width: 8),
                              itemBuilder: (context, i) {
                                final s = _statuses[i];
                                final selected = _statusFilter == s;
                                return ChoiceChip(
                                  label: Text(s == 'All' ? 'All' : statusLabel(s)),
                                  selected: selected,
                                  onSelected: (_) => setState(() => _statusFilter = s),
                                  selectedColor: AppColors.primary,
                                  labelStyle: TextStyle(color: selected ? Colors.white : AppColors.textPrimary, fontSize: 12.5, fontWeight: FontWeight.w600),
                                );
                              },
                            ),
                          ),
                        ),
                        const SizedBox(width: 8),
                        PopupMenuButton<_SortOrder>(
                          icon: const Icon(Icons.sort),
                          tooltip: 'Sort',
                          onSelected: (v) => setState(() => _sort = v),
                          itemBuilder: (context) => const [
                            PopupMenuItem(value: _SortOrder.newest, child: Text('Newest first')),
                            PopupMenuItem(value: _SortOrder.oldest, child: Text('Oldest first')),
                          ],
                        ),
                      ],
                    ),
                  ),
                ),
                if (rfqs.isEmpty)
                  SliverFillRemaining(
                    hasScrollBody: false,
                    child: Center(
                      child: Padding(
                        padding: const EdgeInsets.all(32),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          children: [
                            Container(
                              width: 72,
                              height: 72,
                              decoration: BoxDecoration(color: AppColors.primary.withValues(alpha: 0.08), shape: BoxShape.circle),
                              child: const Icon(Icons.request_quote_outlined, size: 34, color: AppColors.primary),
                            ),
                            const SizedBox(height: 16),
                            Text(all.isEmpty ? 'No RFQs yet' : 'No matching RFQs', style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 16)),
                            const SizedBox(height: 6),
                            Text(
                              all.isEmpty ? 'Tap "New RFQ" to request quotes from exporters.' : 'Try a different search or filter.',
                              textAlign: TextAlign.center,
                              style: const TextStyle(color: AppColors.textSecondary),
                            ),
                          ],
                        ),
                      ),
                    ),
                  )
                else
                  SliverPadding(
                    padding: const EdgeInsets.fromLTRB(16, 8, 16, 96),
                    sliver: SliverList.builder(
                      itemCount: rfqs.length,
                      itemBuilder: (context, i) => _RfqCard(
                        rfq: rfqs[i],
                        onView: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => RFQQuotationsScreen(rfq: rfqs[i]))),
                        onDuplicate: () => _duplicate(rfqs[i]),
                        onShare: () => _share(rfqs[i]),
                        onDownloadPdf: () => _downloadPdf(rfqs[i]),
                        onDownloadDocx: () => _downloadDocx(rfqs[i]),
                        onDownloadImage: () => _downloadImage(rfqs[i]),
                      ),
                    ),
                  ),
              ],
            );
          },
        ),
      ),
    );
  }
}

Color _rfqStatusColor(String status) {
  switch (status) {
    case 'open':
      return AppColors.heldBlue;
    case 'quoted':
      return AppColors.accent;
    case 'closed':
      return AppColors.success;
    case 'cancelled':
      return AppColors.error;
    default:
      return AppColors.textSecondary;
  }
}

/// Premium RFQ card — product, RFQ number, destination, quantity, target price, status
/// badge, created date, and a quick-actions row.
class _RfqCard extends StatelessWidget {
  final RFQ rfq;
  final VoidCallback onView;
  final VoidCallback onDuplicate;
  final VoidCallback onShare;
  final VoidCallback onDownloadPdf;
  final VoidCallback onDownloadDocx;
  final VoidCallback onDownloadImage;

  const _RfqCard({
    required this.rfq,
    required this.onView,
    required this.onDuplicate,
    required this.onShare,
    required this.onDownloadPdf,
    required this.onDownloadDocx,
    required this.onDownloadImage,
  });

  @override
  Widget build(BuildContext context) {
    final color = _rfqStatusColor(rfq.status);
    return TweenAnimationBuilder<double>(
      tween: Tween(begin: 0, end: 1),
      duration: const Duration(milliseconds: 300),
      curve: Curves.easeOut,
      builder: (context, v, child) => Opacity(opacity: v, child: Transform.translate(offset: Offset(0, (1 - v) * 10), child: child)),
      child: Card(
        margin: const EdgeInsets.only(bottom: 12),
        child: InkWell(
          borderRadius: BorderRadius.circular(14),
          onTap: onView,
          child: Padding(
            padding: const EdgeInsets.all(14),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    Container(
                      width: 42,
                      height: 42,
                      decoration: BoxDecoration(color: color.withValues(alpha: 0.12), borderRadius: BorderRadius.circular(12)),
                      child: Icon(Icons.request_quote_outlined, color: color, size: 22),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(rfq.productName, style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 14.5), maxLines: 1, overflow: TextOverflow.ellipsis),
                          const SizedBox(height: 2),
                          Text('${rfq.rfqNumber} · ${rfq.destinationCountry}', style: const TextStyle(color: AppColors.textSecondary, fontSize: 12)),
                        ],
                      ),
                    ),
                    Container(
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                      decoration: BoxDecoration(color: color.withValues(alpha: 0.12), borderRadius: BorderRadius.circular(20)),
                      child: Text(statusLabel(rfq.status), style: TextStyle(color: color, fontWeight: FontWeight.w700, fontSize: 11)),
                    ),
                  ],
                ),
                const SizedBox(height: 10),
                Row(
                  children: [
                    Expanded(child: _stat('Quantity', '${rfq.quantity.toStringAsFixed(0)} ${rfq.unit}')),
                    Expanded(child: _stat('Target Price', rfq.targetPrice != null ? '₹${rfq.targetPrice!.toStringAsFixed(2)}' : 'Not set')),
                    Expanded(child: _stat('Created', _formatDate(rfq.createdAt))),
                  ],
                ),
                const SizedBox(height: 10),
                Divider(height: 1, color: Colors.grey.shade200),
                const SizedBox(height: 6),
                Row(
                  children: [
                    _quickAction(Icons.visibility_outlined, 'View', onView),
                    _quickAction(Icons.copy_outlined, 'Duplicate', onDuplicate),
                    _quickAction(Icons.share_outlined, 'Share', onShare),
                    PopupMenuButton<String>(
                      tooltip: 'Download',
                      icon: const Icon(Icons.download_outlined, size: 18, color: AppColors.primary),
                      onSelected: (v) {
                        switch (v) {
                          case 'pdf': onDownloadPdf(); break;
                          case 'docx': onDownloadDocx(); break;
                          case 'image': onDownloadImage(); break;
                        }
                      },
                      itemBuilder: (context) => const [
                        PopupMenuItem(value: 'pdf', child: Text('Download PDF')),
                        PopupMenuItem(value: 'docx', child: Text('Download DOCX')),
                        PopupMenuItem(value: 'image', child: Text('Download Image')),
                      ],
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _stat(String label, String value) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(label, style: const TextStyle(color: AppColors.textSecondary, fontSize: 10.5)),
        const SizedBox(height: 2),
        Text(value, style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 12.5)),
      ],
    );
  }

  Widget _quickAction(IconData icon, String label, VoidCallback onTap) {
    return Expanded(
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(8),
        child: Padding(
          padding: const EdgeInsets.symmetric(vertical: 6),
          child: Column(
            children: [
              Icon(icon, size: 18, color: AppColors.primary),
              const SizedBox(height: 2),
              Text(label, style: const TextStyle(fontSize: 10, color: AppColors.primary, fontWeight: FontWeight.w600)),
            ],
          ),
        ),
      ),
    );
  }

  String _formatDate(DateTime d) => '${d.day}/${d.month}/${d.year}';
}

/// Minimal off-screen render used only to rasterize a card's RFQ document for "Download
/// Image" from the list (the full interactive report UI lives in create_rfq_screen.dart;
/// this is a lightweight standalone copy of the same visual layout for capture purposes).
class _RfqDocumentPreview extends StatelessWidget {
  final RfqReportData data;
  const _RfqDocumentPreview({required this.data});

  @override
  Widget build(BuildContext context) {
    final d = data;
    return Container(
      color: Colors.white,
      padding: const EdgeInsets.all(20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(gradient: const LinearGradient(colors: [AppColors.primary, Color(0xFF1857C4)]), borderRadius: BorderRadius.circular(10)),
                alignment: Alignment.center,
                child: const Text('OBEI', style: TextStyle(color: Colors.white, fontSize: 10, fontWeight: FontWeight.w800)),
              ),
              const SizedBox(width: 10),
              Expanded(child: Text('RFQ ${d.rfqNumber}', style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 15))),
            ],
          ),
          const SizedBox(height: 12),
          _row('Product', d.productName),
          _row('HS Code', d.hsnCode),
          _row('Quantity', '${d.quantity} ${d.unit}'),
          _row('Target Price', d.targetPrice),
          _row('Destination', d.destinationCountry),
          _row('Status', d.status),
          const SizedBox(height: 8),
          const Text('Generated by ${AppConstants.appName}', style: TextStyle(color: AppColors.textSecondary, fontSize: 9)),
        ],
      ),
    );
  }

  Widget _row(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 3),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: const TextStyle(color: AppColors.textSecondary, fontSize: 11)),
          Text(value, style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 11)),
        ],
      ),
    );
  }
}

/// Quotations received against one RFQ — importer accepts one, which creates the order +
/// escrow. Unchanged from before (same TradeService calls, same accept flow).
class RFQQuotationsScreen extends StatefulWidget {
  final RFQ rfq;
  const RFQQuotationsScreen({super.key, required this.rfq});
  @override
  State<RFQQuotationsScreen> createState() => _RFQQuotationsScreenState();
}

class _RFQQuotationsScreenState extends State<RFQQuotationsScreen> {
  final _tradeService = TradeService();
  final _negotiationService = NegotiationService();
  late Future<List<Quotation>> _future;
  bool _accepting = false;

  @override
  void initState() {
    super.initState();
    _future = _tradeService.listQuotationsForRFQ(widget.rfq.id);
  }

  void _refresh() => setState(() => _future = _tradeService.listQuotationsForRFQ(widget.rfq.id));

  // Unchanged from before — same TradeService call, same accept flow, same order creation.
  Future<void> _accept(Quotation q) async {
    setState(() => _accepting = true);
    try {
      final order = await _tradeService.acceptQuotation(q.id);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Order ${order.orderNumber} created. Go to your dashboard to pay into escrow.'), backgroundColor: AppColors.success),
        );
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('$e'), backgroundColor: AppColors.error));
    } finally {
      if (mounted) setState(() => _accepting = false);
    }
  }

  // New — Negotiation Engine entry points. Purely additive: neither touches the quotation
  // accept flow above, both go through the new /negotiations/* endpoints only.
  Future<void> _reject(Quotation q) async {
    setState(() => _accepting = true);
    try {
      await _negotiationService.rejectQuotation(q.id);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Quotation rejected'), backgroundColor: AppColors.success));
        _refresh();
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('$e'), backgroundColor: AppColors.error));
    } finally {
      if (mounted) setState(() => _accepting = false);
    }
  }

  Future<void> _negotiate(Quotation q) async {
    setState(() => _accepting = true);
    try {
      final negotiation = await _negotiationService.start(q.id);
      if (mounted) {
        await Navigator.of(context).push(MaterialPageRoute(builder: (_) => NegotiationScreen(negotiationId: negotiation.id, rfq: widget.rfq)));
        _refresh();
      }
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('$e'), backgroundColor: AppColors.error));
    } finally {
      if (mounted) setState(() => _accepting = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.rfq.rfqNumber)),
      body: FutureBuilder<List<Quotation>>(
        future: _future,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.waiting) {
            return const Center(child: CircularProgressIndicator());
          }
          if (snapshot.hasError) {
            return Center(child: Text('Error: ${snapshot.error}'));
          }
          final quotations = snapshot.data ?? [];
          if (quotations.isEmpty) {
            return const Center(child: Text('No quotations received yet.', style: TextStyle(color: AppColors.textSecondary)));
          }
          return ListView.builder(
            padding: const EdgeInsets.all(16),
            itemCount: quotations.length,
            itemBuilder: (context, i) {
              final q = quotations[i];
              return Card(
                margin: const EdgeInsets.only(bottom: 12),
                child: Padding(
                  padding: const EdgeInsets.all(14),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text('₹${q.unitPrice.toStringAsFixed(2)} / unit', style: const TextStyle(fontWeight: FontWeight.w700, fontSize: 16)),
                          Chip(label: Text(statusLabel(q.status)), backgroundColor: statusColor(q.status).withValues(alpha: 0.12), labelStyle: TextStyle(color: statusColor(q.status))),
                        ],
                      ),
                      const SizedBox(height: 6),
                      Text('Total: ₹${q.totalAmount.toStringAsFixed(2)} · Qty: ${q.quantity}', style: const TextStyle(color: AppColors.textSecondary)),
                      Text('Valid until: ${q.validityDate.toLocal().toString().split(' ').first}', style: const TextStyle(color: AppColors.textSecondary, fontSize: 13)),
                      if (q.terms != null && q.terms!.isNotEmpty) ...[
                        const SizedBox(height: 6),
                        Text(q.terms!),
                      ],
                      if (q.status == 'pending') ...[
                        const SizedBox(height: 10),
                        SizedBox(
                          width: double.infinity,
                          child: ElevatedButton(
                            onPressed: _accepting ? null : () => _accept(q),
                            child: const Text('Accept Quotation'),
                          ),
                        ),
                        const SizedBox(height: 8),
                        Row(
                          children: [
                            Expanded(
                              child: OutlinedButton(
                                onPressed: _accepting ? null : () => _reject(q),
                                style: OutlinedButton.styleFrom(foregroundColor: AppColors.error, side: const BorderSide(color: AppColors.error)),
                                child: const Text('Reject'),
                              ),
                            ),
                            const SizedBox(width: 8),
                            Expanded(
                              child: OutlinedButton.icon(
                                onPressed: _accepting ? null : () => _negotiate(q),
                                icon: const Icon(Icons.swap_horiz, size: 16),
                                label: const Text('Negotiate'),
                              ),
                            ),
                          ],
                        ),
                      ],
                    ],
                  ),
                ),
              );
            },
          );
        },
      ),
    );
  }
}
