package services

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"fmt"

	"github.com/jayashri-infotech/onebharat-backend/internal/models"
	"github.com/jayashri-infotech/onebharat-backend/internal/repository"
	"github.com/jayashri-infotech/onebharat-backend/pkg/security"
	"github.com/jayashri-infotech/onebharat-backend/pkg/storage"
	"github.com/jung-kurt/gofpdf"
)

type DocumentService struct {
	docRepo       *repository.DocumentRepository
	orderRepo     *repository.OrderRepository
	userRepo      *repository.UserRepository
	shipmentRepo  *repository.ShipmentRepository
	storage       storage.StorageService
	docSecurity   *DocumentSecurityService
	signingSecret string
}

func NewDocumentService(docRepo *repository.DocumentRepository, orderRepo *repository.OrderRepository, userRepo *repository.UserRepository, shipmentRepo *repository.ShipmentRepository, storageService storage.StorageService, docSecurity *DocumentSecurityService, signingSecret string) *DocumentService {
	return &DocumentService{docRepo: docRepo, orderRepo: orderRepo, userRepo: userRepo, shipmentRepo: shipmentRepo, storage: storageService, docSecurity: docSecurity, signingSecret: signingSecret}
}

// sign — HMAC-SHA256 over the document bytes, keyed by the platform's signing secret. This is
// the "digital signature" Journey 9 requires: proof the document was generated by this
// platform and hasn't been tampered with since — verify by recomputing the HMAC and comparing.
// Not an X.509/PKI signature (no per-user certificate authority exists in this system), but a
// genuine cryptographic signature over the exact bytes served.
func (s *DocumentService) sign(data []byte) string {
	mac := hmac.New(sha256.New, []byte(s.signingSecret))
	mac.Write(data)
	return hex.EncodeToString(mac.Sum(nil))
}

// Generate — renders the requested trade document as a PDF from the order's data and stores
// it via the shared StorageService (Journey 9 "store securely": encrypted at rest when
// DOCUMENT_ENCRYPTION_KEY is set, same pipeline as KYC/compliance/chat uploads — not raw local
// disk + a public static route like before). Every generation is a new, checksummed,
// HMAC-signed version, kept in document_versions ("version history") rather than overwriting
// the previous file. Importer/exporter can generate any type; the assigned logistics partner
// can additionally generate the shipment-related documents.
func (s *DocumentService) Generate(ctx context.Context, orderID string, docType models.DocumentType, generatedBy string) (*models.Document, error) {
	order, err := s.orderRepo.GetByID(ctx, orderID)
	if err != nil {
		return nil, err
	}

	authorized := generatedBy == order.ImporterID || generatedBy == order.ExporterID
	if !authorized && (docType == models.DocBillOfLading || docType == models.DocAirWaybill || docType == models.DocShippingInvoice) {
		shipment, shipErr := s.shipmentRepo.GetByOrderID(ctx, orderID)
		if shipErr == nil && shipment != nil && shipment.LogisticsID != nil && *shipment.LogisticsID == generatedBy {
			authorized = true
		}
	}
	if !authorized {
		return nil, fmt.Errorf("not authorized to generate documents for this order")
	}
	importer, err := s.userRepo.GetByID(ctx, order.ImporterID)
	if err != nil {
		return nil, err
	}
	exporter, err := s.userRepo.GetByID(ctx, order.ExporterID)
	if err != nil {
		return nil, err
	}

	existing, err := s.docRepo.GetByOrderAndType(ctx, orderID, docType)
	if err != nil {
		return nil, fmt.Errorf("checking existing document: %w", err)
	}
	nextVersion := 1
	if existing != nil {
		nextVersion = existing.Version + 1
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	renderDocument(pdf, docType, order, importer, exporter)
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("render pdf: %w", err)
	}
	pdfBytes := buf.Bytes()

	checksum := security.SHA256Hex(pdfBytes)
	signature := s.sign(pdfBytes)
	storageKey := fmt.Sprintf("documents/%s/%s_v%d.pdf", orderID, docType, nextVersion)

	if err := s.storage.Upload(ctx, storageKey, "application/pdf", bytes.NewReader(pdfBytes)); err != nil {
		return nil, fmt.Errorf("store document: %w", err)
	}

	doc := &models.Document{
		OrderID:     order.ID,
		Type:        docType,
		StorageKey:  storageKey,
		Version:     nextVersion,
		Checksum:    checksum,
		Signature:   signature,
		GeneratedBy: generatedBy,
	}
	if err := s.docRepo.Upsert(ctx, doc); err != nil {
		return nil, fmt.Errorf("save document record: %w", err)
	}
	if err := s.docRepo.AddVersion(ctx, &models.DocumentVersion{
		DocumentID: doc.ID, Version: nextVersion, StorageKey: storageKey,
		Checksum: checksum, Signature: signature, GeneratedBy: generatedBy,
	}); err != nil {
		return nil, fmt.Errorf("save document version history: %w", err)
	}
	return doc, nil
}

// ListForOrder — baseURL (scheme+host of the requesting client, same pattern as
// SecurityHandler) is used to build a fresh signed download URL per document on every call
// (Journey 9 "signed sharing") — URLs are never stored, so they can't go stale/leak a
// permanent public path.
// SECURITY FIX (document ownership validation): previously had no authorization check at
// all — any authenticated user could list and download every generated trade document
// (commercial invoice, packing list, bill of lading, etc.) for any order by knowing/guessing
// an order_id. Now requires the requester to be that order's own importer/exporter, matching
// the check ListVersions/Delete already had.
func (s *DocumentService) ListForOrder(ctx context.Context, orderID, requesterID, baseURL string) ([]models.Document, error) {
	if err := s.authorizeOrderAccess(ctx, orderID, requesterID); err != nil {
		return nil, err
	}
	docs, err := s.docRepo.ListByOrder(ctx, orderID)
	if err != nil {
		return nil, err
	}
	for i := range docs {
		docs[i].FileURL = s.docSecurity.GenerateDownloadUrl(docs[i].StorageKey, baseURL)
	}
	return docs, nil
}

// ListVersions — Journey 9 "version history": every past generation of one document, each
// with its own signed download URL and checksum/signature for that exact version's bytes.
func (s *DocumentService) ListVersions(ctx context.Context, documentID, requesterID, baseURL string) ([]models.DocumentVersion, error) {
	doc, err := s.docRepo.GetByID(ctx, documentID)
	if err != nil {
		return nil, err
	}
	if doc == nil {
		return nil, fmt.Errorf("document not found")
	}
	if err := s.authorizeOrderAccess(ctx, doc.OrderID, requesterID); err != nil {
		return nil, err
	}
	versions, err := s.docRepo.ListVersions(ctx, documentID)
	if err != nil {
		return nil, err
	}
	for i := range versions {
		versions[i].FileURL = s.docSecurity.GenerateDownloadUrl(versions[i].StorageKey, baseURL)
	}
	return versions, nil
}

// Delete — Journey 9 "no orphan files": removes every version's stored object before removing
// the DB rows (CASCADE handles document_versions), so nothing is left in storage with no
// tracking record pointing to it.
func (s *DocumentService) Delete(ctx context.Context, documentID, requesterID string) error {
	doc, err := s.docRepo.GetByID(ctx, documentID)
	if err != nil {
		return err
	}
	if doc == nil {
		return fmt.Errorf("document not found")
	}
	if err := s.authorizeOrderAccess(ctx, doc.OrderID, requesterID); err != nil {
		return err
	}
	versions, err := s.docRepo.ListVersions(ctx, documentID)
	if err != nil {
		return err
	}
	for _, v := range versions {
		_ = s.storage.Delete(ctx, v.StorageKey) // best-effort; a missing key is not an error either way
	}
	return s.docRepo.Delete(ctx, documentID)
}

func (s *DocumentService) authorizeOrderAccess(ctx context.Context, orderID, requesterID string) error {
	order, err := s.orderRepo.GetByID(ctx, orderID)
	if err != nil {
		return err
	}
	if requesterID != order.ImporterID && requesterID != order.ExporterID {
		return fmt.Errorf("not authorized for this order's documents")
	}
	return nil
}

func renderDocument(pdf *gofpdf.Fpdf, docType models.DocumentType, order *models.Order, importer, exporter *models.User) {
	pdf.SetFont("Arial", "B", 16)
	pdf.Cell(0, 10, documentTitle(docType))
	pdf.Ln(14)

	pdf.SetFont("Arial", "", 11)
	pdf.CellFormat(0, 7, fmt.Sprintf("Order Number: %s", order.OrderNumber), "", 1, "L", false, 0, "")
	pdf.CellFormat(0, 7, fmt.Sprintf("Date: %s", order.CreatedAt.Format("02-Jan-2006")), "", 1, "L", false, 0, "")
	pdf.Ln(4)

	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(0, 7, "Exporter", "", 1, "L", false, 0, "")
	pdf.SetFont("Arial", "", 11)
	pdf.CellFormat(0, 6, exporter.FullName, "", 1, "L", false, 0, "")
	if exporter.CompanyName != nil {
		pdf.CellFormat(0, 6, *exporter.CompanyName, "", 1, "L", false, 0, "")
	}
	pdf.Ln(4)

	pdf.SetFont("Arial", "B", 12)
	pdf.CellFormat(0, 7, "Importer / Consignee", "", 1, "L", false, 0, "")
	pdf.SetFont("Arial", "", 11)
	pdf.CellFormat(0, 6, importer.FullName, "", 1, "L", false, 0, "")
	if importer.CompanyName != nil {
		pdf.CellFormat(0, 6, *importer.CompanyName, "", 1, "L", false, 0, "")
	}
	if order.DeliveryAddress != nil {
		pdf.MultiCell(0, 6, *order.DeliveryAddress, "", "L", false)
	}
	pdf.Ln(6)

	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(70, 8, "Description", "1", 0, "L", false, 0, "")
	pdf.CellFormat(30, 8, "HSN Code", "1", 0, "C", false, 0, "")
	pdf.CellFormat(30, 8, "Quantity", "1", 0, "C", false, 0, "")
	pdf.CellFormat(30, 8, "Unit Price", "1", 0, "C", false, 0, "")
	pdf.CellFormat(30, 8, "Amount", "1", 1, "C", false, 0, "")

	pdf.SetFont("Arial", "", 11)
	hsn := ""
	if order.HSNCode != nil {
		hsn = *order.HSNCode
	}
	pdf.CellFormat(70, 8, order.ProductName, "1", 0, "L", false, 0, "")
	pdf.CellFormat(30, 8, hsn, "1", 0, "C", false, 0, "")
	pdf.CellFormat(30, 8, fmt.Sprintf("%.2f %s", order.Quantity, order.Unit), "1", 0, "C", false, 0, "")
	pdf.CellFormat(30, 8, fmt.Sprintf("%.2f", order.UnitPrice), "1", 0, "R", false, 0, "")
	pdf.CellFormat(30, 8, fmt.Sprintf("%.2f", order.TotalAmount), "1", 1, "R", false, 0, "")

	pdf.Ln(6)
	pdf.SetFont("Arial", "B", 11)
	pdf.CellFormat(0, 7, fmt.Sprintf("Total: %s %.2f", order.Currency, order.TotalAmount), "", 1, "R", false, 0, "")

	if docType == models.DocCertificateOfOrigin {
		pdf.Ln(10)
		pdf.SetFont("Arial", "", 11)
		pdf.MultiCell(0, 6, "It is hereby certified that the goods described above originate in India, in accordance with the applicable rules of origin.", "", "L", false)
	}
	if docType == models.DocInsuranceCertificate {
		pdf.Ln(10)
		pdf.SetFont("Arial", "", 11)
		pdf.MultiCell(0, 6, "This certifies that the shipment described above is insured against loss or damage in transit, for the full invoice value, in accordance with the agreed Incoterms.", "", "L", false)
	}
	if docType == models.DocInspectionCertificate {
		pdf.Ln(10)
		pdf.SetFont("Arial", "", 11)
		pdf.MultiCell(0, 6, "This certifies that the goods described above have been inspected and found to conform to the agreed quality and quantity specifications prior to shipment.", "", "L", false)
	}
	if docType == models.DocExportDeclaration {
		pdf.Ln(10)
		pdf.SetFont("Arial", "", 11)
		pdf.MultiCell(0, 6, "Declaration filed by the exporter with the customs authority of the country of origin, authorizing the goods described above to leave the country.", "", "L", false)
	}
	if docType == models.DocImportDeclaration {
		pdf.Ln(10)
		pdf.SetFont("Arial", "", 11)
		pdf.MultiCell(0, 6, "Declaration filed by the importer with the customs authority of the destination country, declaring the goods described above for entry.", "", "L", false)
	}

	pdf.Ln(20)
	pdf.SetFont("Arial", "", 10)
	pdf.CellFormat(0, 6, "Generated by One Bharat Export Import platform. This document is digitally signed and electronically issued.", "", 1, "L", false, 0, "")
}

func documentTitle(t models.DocumentType) string {
	switch t {
	case models.DocCommercialInvoice:
		return "Commercial Invoice"
	case models.DocPackingList:
		return "Packing List"
	case models.DocCertificateOfOrigin:
		return "Certificate of Origin"
	case models.DocBillOfLading:
		return "Bill of Lading"
	case models.DocAirWaybill:
		return "Air Waybill"
	case models.DocShippingInvoice:
		return "Shipping Invoice"
	case models.DocExportDeclaration:
		return "Export Declaration"
	case models.DocImportDeclaration:
		return "Import Declaration"
	case models.DocInspectionCertificate:
		return "Inspection Certificate"
	case models.DocInsuranceCertificate:
		return "Insurance Certificate"
	default:
		return "Trade Document"
	}
}
